version: "3.9"
services:
  app:
    image: gotodo
    build:
      args:
        - target=deploy-builder
    environment:
      TODO_ENV: prod
      PORT: 8080
      TODO_DB_HOST: tododb01
      TODO_DB_PORT: 3306
      TODO_DB_USER: todo
      TODO_DB_PASSWORD: P@ssw0rd
      TODO_DB_NAME: todo
    volumes:
      - .:/app
    ports:
      - '8080:8080'
  tododb01:
    image: mysql:8.0.29
    platform: linux/amd64
    container_name:  tododb01
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: todo
      MYSQL_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: todo
      MYSQL_TCP_PORT: 3306
    volumes:
      - tododb01-data:/var/lib/mysql
      - $PWD/_tools/mysql/conf.d:/etc/mysql/conf.d:cached
    ports:
      - '3306:3306'
volumes:
  tododb01-data: